// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjllnwANFefp4D3lM1ViCgdGfNnnxODm4',
    appId: '1:177872037232:web:fe684e936d55384d0c9bb5',
    messagingSenderId: '177872037232',
    projectId: 'steelsoul-9e68a',
    authDomain: 'steelsoul-9e68a.firebaseapp.com',
    storageBucket: 'steelsoul-9e68a.firebasestorage.app',
    measurementId: 'G-0MCQHQQQGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNDIOw-Ptey42RZfb_frlHyvDVeLFSl0k',
    appId: '1:177872037232:android:6d6f14c64e59f0750c9bb5',
    messagingSenderId: '177872037232',
    projectId: 'steelsoul-9e68a',
    storageBucket: 'steelsoul-9e68a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKlO2Wm8ad1kBH1i0NW9cAV5yP-wDXjmI',
    appId: '1:177872037232:ios:3358af320f096bc60c9bb5',
    messagingSenderId: '177872037232',
    projectId: 'steelsoul-9e68a',
    storageBucket: 'steelsoul-9e68a.firebasestorage.app',
    iosBundleId: 'com.example.steelSoul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKlO2Wm8ad1kBH1i0NW9cAV5yP-wDXjmI',
    appId: '1:177872037232:ios:3358af320f096bc60c9bb5',
    messagingSenderId: '177872037232',
    projectId: 'steelsoul-9e68a',
    storageBucket: 'steelsoul-9e68a.firebasestorage.app',
    iosBundleId: 'com.example.steelSoul',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjllnwANFefp4D3lM1ViCgdGfNnnxODm4',
    appId: '1:177872037232:web:4493562ca6cb3d7e0c9bb5',
    messagingSenderId: '177872037232',
    projectId: 'steelsoul-9e68a',
    authDomain: 'steelsoul-9e68a.firebaseapp.com',
    storageBucket: 'steelsoul-9e68a.firebasestorage.app',
    measurementId: 'G-JFHQWBWGTS',
  );
}
